### ISSUE TITLE
When initializing slices/arrays (with values), can't have final closed brace on it's own line

### ISSUE THREAD

**Issue by corpusc** [skycoin/cx#167] opened 2020-12-11 02:03 UTC
When initializing slices/arrays (with values), can't have final closed brace on it's own line

Describe:

i find the neatest way to do this is like:

package main

func main() {
    var s [3]str = [3]str{
        "a",
        "b",
        "c"
    }
}

To Reproduce

Enter code above

Expected behavior
I'd like to format my code like this for neatness, and have it work with no error.

ERROR REPORT
c.cx:7: syntax error: unexpected SEMICOLON
(points to the last data element "c")

**Comment by SkycoinSynth** [comment] 2021-02-04 08:11
"Unexpected semi-colon" is clearly wrong error message.

**Comment by SkycoinSynth** [comment] 2021-03-19 06:50
Moved to readme.

**Comment by SkycoinSynth** [comment] 2021-03-19 06:50
Duplicate of #38

**Closed as completed** 2021-03-19 06:49 UTC
